services:
  redis:
    image: redis:7-alpine
    container_name: palm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - palm-network

  postgres:
    image: postgres:16-alpine
    container_name: palm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-palm}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-palm}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - palm-network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  palm-network:
    driver: bridge
