# fly.toml app configuration file generated for app-geoffjay-com on 2025-09-16T22:59:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-geoffjay-com'
primary_region = 'yyz'

[build]
dockerfile = "Dockerfile"

[deploy]
release_command = "bash -c 'NODE_ENV=production bun run db:migrate'"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
