app = 'app-geoffjay-com-redis'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile'

[env]
  # Redis doesn't need special env vars for basic operation

[[services]]
  protocol = 'tcp'
  internal_port = 6379

  [[services.ports]]
    port = 6379
    handlers = []

  # Health checks
  [[services.tcp_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'

# Mount for Redis data persistence
[[mounts]]
  source = 'redis_data'
  destination = '/data'
  initial_size = '1gb'
