app = 'app-geoffjay-com-redis'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile'

[env]
  # REDIS_PASSWORD set via fly secrets


# Public service with TLS
[[services]]
  internal_port = 6379
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 6379
    handlers = []

  # Health check
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"

# Mount for Redis data persistence
[[mounts]]
  source = 'redis_data'
  destination = '/data'
  initial_size = '1gb'
